kind: pipeline
name: default

steps:
- name: run_python_unit_test
  image: python:3.7.4-alpine3.10
  commands:
  - pip install -r requirements.txt
  - coverage run -m unittest
  environment:
    TEST_FILES_LOCATION: test/test_files

- name: codecov
  image: python:3.7.4-alpine3.10
  commands:
  - pip install codecov
  - codecov -t $TOKEN
  environment:
    TOKEN:
      from_secret: codecov_token