kind: pipeline
name: default

steps:
- name: run_python_unit_test
  image: python:3.7.4-alpine3.10
  commands:
  - pip install -r requirements.txt
  - coverage run -m unittest
  - codecov  --commit=$DRONE_COMMIT_SHA
  environment:
    TEST_FILES_LOCATION: test/test_files
    codecov_token:
      from_secret: codecov_token
