kind: pipeline
name: default

steps:
- name: run_python_unit_test
  image: python:3.7.4-alpine3.10
  commands:
  - pip install -r requirements.txt
  - pip install codecov
  - coverage run -m unittest
  - codecov
  environment:
    TEST_FILES_LOCATION: test/test_files

  codecov:
      image: robertstettner/drone-codecov
      secrets: [ codecov_token ]